import {PasswordInput} from './PasswordInput';
import React, {useEffect,useState} from 'react';
import {supabase} from './client';
import type {Profile} from './cloud';
export async function schoolLoginEmail(school:string,login:string){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${school.trim().toLowerCase()}\0${login.trim().toLowerCase()}`));return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')+'@accounts.lti.invalid';}
async function accountAction(body:Record<string,unknown>){
 const {data,error}=await supabase.functions.invoke('lti-accounts',{body});
 if(error){let message='アカウント処理を完了できませんでした。';try{const result=await error.context?.json();message=result?.error||message;}catch{}throw new Error(message);}
 if(data?.error)throw new Error(data.error);return data;
}
export function PasswordChange({onDone,onCancel}:{onDone:()=>void;onCancel?:()=>void}){
 const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [again,setAgain]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 return <div className="max-w-lg mx-auto bg-white p-8 rounded-2xl border space-y-4"><h2 className="text-xl font-bold">パスワードを変更してください</h2><p className="text-sm">初期・再発行パスワードでは研究データを開けません。自分だけが知っている12文字以上のパスワードに変更してください。</p><form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(next!==again){setError('新しいパスワードが一致しません');return;}setBusy(true);setError('');try{const {data:{user}}=await supabase.auth.getUser();await accountAction({action:'change-password',currentPassword:current,newPassword:next});await supabase.auth.signOut({scope:'local'});if(user?.email){const signed=await supabase.auth.signInWithPassword({email:user.email,password:next});if(signed.error)throw signed.error;}setCurrent('');setNext('');setAgain('');onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <label className="block text-sm">現在のパスワード<PasswordInput required autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} className="block w-full border p-3 rounded-xl"/></label>
 <label className="block text-sm">新しいパスワード<PasswordInput required minLength={12} maxLength={128} autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} className="block w-full border p-3 rounded-xl"/></label>
 <label className="block text-sm">もう一度入力<PasswordInput required minLength={12} maxLength={128} autoComplete="new-password" value={again} onChange={e=>setAgain(e.target.value)} className="block w-full border p-3 rounded-xl"/></label>
 <button disabled={busy} className="bg-emerald-700 text-white rounded-xl p-3">{busy?'変更中…':'変更して続ける'}</button></form>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{onCancel&&<button disabled={busy} onClick={onCancel}>閉じる</button>}</div>;
}
export function MfaSetup({onDone,onCancel}:{onDone:()=>void;onCancel?:()=>void}){
 const [factor,setFactor]=useState('');const [qr,setQr]=useState('');const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [checked,setChecked]=useState(false);
 useEffect(()=>{let alive=true;supabase.auth.mfa.listFactors().then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else setFactor(data.totp.find(f=>f.status==='verified')?.id||'');setChecked(true);});return()=>{alive=false;};},[]);
 return <div className="max-w-lg mx-auto p-8 bg-white border rounded-2xl space-y-4"><h2 className="font-bold text-xl">二段階認証</h2><p className="text-sm">認証アプリの6桁コードを使用します。メールの受信は必要ありません。LTI管理者には必須です。</p>
 {checked&&!factor&&<button disabled={busy} className="bg-emerald-100 rounded-xl p-3" onClick={async()=>{setBusy(true);setError('');const r=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'LTI '+new Date().toISOString()});setBusy(false);if(r.error){setError(r.error.message);return;}setFactor(r.data.id);setQr(r.data.totp.qr_code);}}>認証アプリを登録</button>}
 {qr&&<><img src={qr.startsWith('data:')?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`} alt="認証アプリ登録用QRコード" className="w-56 h-56"/><p className="text-xs">QRコードを他の人と共有しないでください。端末を失った場合は本人確認を伴う復旧が必要です。</p></>}
 {factor&&<form className="space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const r=await supabase.auth.mfa.challengeAndVerify({factorId:factor,code});setBusy(false);if(r.error)setError(r.error.message);else{setCode('');onDone();}}}><label className="block">6桁の確認コード<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className="block border rounded-xl p-3"/></label><button disabled={busy} className="bg-emerald-700 text-white p-3 rounded-xl">確認する</button></form>}
 {error&&<p role="alert" className="text-red-700 text-sm">{error}</p>}{onCancel&&<button onClick={onCancel}>戻る</button>}</div>;
}
type Credential={schoolId:string;loginId:string;initialPassword:string;expiresAt:string};
export function AccountManagement({profiles,schools,profile,reload}:{profiles:Profile[];schools:{id:string;name:string}[];profile:Profile;reload:()=>Promise<void>}){
 const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [credentials,setCredentials]=useState<Credential[]>([]);const [notice,setNotice]=useState('');
 const run=async(work:()=>Promise<any>)=>{setBusy(true);setError('');try{const r=await work();if(r?.error)throw r.error;await reload();return r;}catch(e){setError((e as Error).message||'保存に失敗しました');}finally{setBusy(false);}};
 const receive=(r:any)=>{if(!r)return;setCredentials(r.credentials||[]);setNotice(r.failures?.length?`${r.failures.length}件の発行に失敗しました。成功した分を配布し、利用者一覧を確認してください。`:'発行しました。初期パスワードを再表示することはできません。必要な分を保存・配布してください。');};
 const csv=()=>{const cell=(v:string)=>'"'+(/^[=+\-@\t\r]/.test(v)?"'"+v:v).replace(/"/g,'""')+'"';const data='\uFEFF学校ID,ログインID,初期パスワード,有効期限\r\n'+credentials.map(c=>[c.schoolId,c.loginId,c.initialPassword,c.expiresAt].map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='LTI-login-cards.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const close=()=>{if(credentials.length&&!window.confirm('初期パスワードの表示を閉じます。配布用データを保存しましたか？'))return;setCredentials([]);setOpen(false);};
 return <><button onClick={()=>setOpen(true)} className="underline">学校・利用者管理</button>{open&&<div className="fixed inset-0 z-[85] bg-black/40 overflow-auto p-6"><div className="max-w-4xl mx-auto bg-white p-6 rounded-2xl space-y-5"><button disabled={busy} onClick={close}>閉じる</button><h2 className="text-xl font-bold">学校・利用者管理</h2>
 <form className="flex flex-wrap gap-2" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await run(()=>accountAction({action:'create-school',name:f.get('name'),schoolId:f.get('schoolId')}));if(r)setNotice(`学校を追加しました：${r.school.name} / 学校ID ${r.school.id}`);}}><input name="schoolId" required pattern="[a-z0-9][a-z0-9-]{1,29}" maxLength={30} aria-label="指定する学校ID" placeholder="学校ID（例：sakura）" className="border p-3 rounded-xl"/><input name="name" required maxLength={100} aria-label="学校名" placeholder="新しく契約した学校名" className="border p-3 rounded-xl"/><button disabled={busy} className="bg-emerald-100 p-3 rounded-xl">学校IDを発行</button></form>
 <form className="flex flex-wrap gap-2" onSubmit={async e=>{e.preventDefault();if(credentials.length&&!window.confirm('前回分の初期パスワードを保存しましたか？'))return;const f=new FormData(e.currentTarget);receive(await run(()=>accountAction({action:'create-accounts',schoolId:f.get('school'),role:f.get('role'),count:Number(f.get('count')),requestId:crypto.randomUUID()})));}}><select name="school" required aria-label="発行先の学校" className="border p-3 rounded-xl"><option value="">学校を選択</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}（{s.id}）</option>)}</select><select name="role" aria-label="利用者種別" className="border p-3 rounded-xl"><option value="student">生徒</option><option value="teacher">教員</option></select><input name="count" required type="number" min={1} max={20} defaultValue={1} aria-label="発行人数" className="border p-3 rounded-xl w-24"/><button disabled={busy} className="bg-emerald-700 text-white p-3 rounded-xl">アカウントを発行</button></form><p className="text-xs">1回につき20人まで発行できます。ログインIDは学校ごとに自動採番します。初期パスワードの有効期限は7日です。</p>
 {notice&&<p role="status" className="text-sm">{notice}</p>}{credentials.length>0&&<section className="border border-amber-300 bg-amber-50 p-4 rounded-xl space-y-3"><h3 className="font-bold">今回発行した初期パスワード</h3><p className="text-xs">一覧は担当者だけで扱い、各本人には自分の分だけを配布してください。配布後のCSVは適切に削除してください。</p><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th>学校ID</th><th>ログインID</th><th>初期パスワード</th></tr></thead><tbody>{credentials.map(c=><tr key={c.schoolId+c.loginId}><td className="p-2">{c.schoolId}</td><td className="p-2">{c.loginId}</td><td className="p-2 font-mono">{c.initialPassword}</td></tr>)}</tbody></table></div><button onClick={csv} className="p-2 bg-white border rounded-lg">配布用CSVを保存</button></section>}
 <h3 className="font-bold">学校の契約終了</h3><p className="text-xs">削除は利用停止と一覧からの除外です。提出済みデータは保持し、学校IDを再利用しません。</p>{schools.map(s=><div key={s.id} className="flex gap-3"><span>{s.name}（{s.id}）</span><button disabled={busy} className="text-red-700" onClick={async()=>{const count=profiles.filter(p=>p.school_id===s.id).length;if(window.prompt(`${s.name} の ${count} 人を利用停止して一覧から削除します。確認のため学校IDを入力してください。`)!==s.id)return;await run(()=>accountAction({action:'retire-school',schoolId:s.id}));}}>学校を削除・契約終了</button></div>)}<h3 className="font-bold">利用者一覧</h3>{profiles.map(p=><form key={[p.id,p.school_id,p.role,p.active].join(':')} className="border p-3 rounded-xl space-y-2" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>Promise.resolve(supabase.rpc('lti_set_membership',{target_id:p.id,new_school:f.get('school')||null,new_role:f.get('role'),enabled:f.get('active')==='on'})));}}>{p.role!=='admin'&&<button type="button" disabled={busy} className="text-red-700" onClick={async()=>{if(!window.confirm(`${p.name}（${p.login_id||p.id}）を利用停止して一覧から削除します。提出物は保持されます。`))return;await run(()=>accountAction({action:'retire-account',userId:p.id}));}}>卒業・退職による削除</button>}{p.role==='student'&&<button type="button" className="underline" onClick={async()=>{const className=window.prompt('クラス',p.class);if(className===null)return;const number=window.prompt('出席番号',String(p.attendance_number||''));if(!number)return;await run(()=>accountAction({action:'set-attendance',userId:p.id,class:className,number:Number(number)}));}}>クラス・出席番号を設定</button>}<p className="break-all">{p.name||'未設定'} / {p.login_id||p.id}</p><select name="school" aria-label="学校" defaultValue={p.school_id||''} disabled={!!p.login_id} className="border p-2"><option value="">学校なし（運営のみ）</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{p.login_id&&<input type="hidden" name="school" value={p.school_id||''}/>}<select name="role" aria-label="権限" defaultValue={p.role} className="border p-2"><option value="student">生徒</option><option value="teacher">教員</option>{!p.login_id&&<option value="admin">LTI運営</option>}</select><label><input type="checkbox" name="active" defaultChecked={p.active}/>利用を許可</label><button disabled={busy||p.id===profile.id} className="p-2 bg-emerald-100 rounded-lg disabled:opacity-40">設定を保存</button>{p.login_id&&p.role!=='admin'&&<button type="button" disabled={busy} className="p-2 text-red-700" onClick={async()=>{if(!window.confirm('本人確認を行いましたか？再発行すると旧パスワードでの研究データへのアクセスを止めます。'))return;receive(await run(()=>accountAction({action:'reset-password',userId:p.id})));}}>初期パスワードを再発行</button>}</form>)}{error&&<p role="alert" className="text-red-700 text-sm">{error}</p>}</div></div>}</>;
}
