import React,{useState} from 'react';
import {distribution,paperDate,selectPapers,rate,type AnalyticsPaper} from './analytics-data';
import type {Profile} from './cloud';
function Bars({rows}:{rows:ReturnType<typeof distribution>}){return rows.length?<div className="space-y-4">{rows.map(r=><div key={r.label}><div className="flex justify-between text-sm gap-4"><span>{r.label}</span><span>{r.count}件・{r.percent.toFixed(1)}%</span></div><div className="bg-gray-100 rounded-full h-2 mt-2"><div className="bg-indigo-500 rounded-full h-2" style={{width:`${r.percent}%`}}/></div></div>)}</div>:<p className="text-sm text-gray-500 py-5">集計対象の論文はまだありません。</p>;}
export function PublishedFields({papers}:{papers:AnalyticsPaper[]}){const published=papers.filter(p=>p.status==='公開中');return <section className="bg-white p-6 rounded-2xl border shadow-sm space-y-4"><h3 className="font-bold text-sm">公開論文の分野比率</h3><p className="text-xs text-gray-500">現在公開中の{published.length}件を100%として計算。公開停止・承認待ちは含みません。</p><Bars rows={distribution(published,'field')}/></section>;}
type Props={papers:AnalyticsPaper[];schools:{id:string;name:string}[];profiles:Profile[];rows:{kind:string;data:any}[];page:string;reload:()=>Promise<void>};
export function AdminAnalytics({papers,schools,profiles,rows,page,reload}:Props){
 const [school,setSchool]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [busy,setBusy]=useState(false);
 const invalid=!!from&&!!to&&from>to;const selected=invalid?[]:selectPapers(papers,school,from,to);const published=selected.filter(p=>p.status==='公開中');
 const schoolNames=new Map(papers.map(p=>[p.schoolId,p.schoolName||p.schoolId]));for(const s of schools)schoolNames.set(s.id,s.name);
 const months=new Map<string,{total:number;published:number}>();for(const p of selected){const date=paperDate(p.submittedDate);const label=date?.slice(0,7)||'日付不明';const m=months.get(label)||{total:0,published:0};m.total++;if(p.status==='公開中')m.published++;months.set(label,m);}
 const bySchool=[...schoolNames].filter(([id])=>!school||id===school).map(([id,name])=>{const all=selected.filter(p=>p.schoolId===id);return {id,name,total:all.length,published:all.filter(p=>p.status==='公開中').length,pending:all.filter(p=>p.status==='承認待ち').length};}).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,'ja'));
 const schoolRows=rows.filter(r=>!school||r.data.schoolId===school);const currentUsers=profiles.filter(p=>p.active&&!p.deleted_at&&(!school||p.school_id===school));
 const unknown=papers.filter(p=>(!school||p.schoolId===school)&&!paperDate(p.submittedDate)).length;
 const csv=()=>{const cells:(string|number)[][]=[['学校','申請開始日',from||'指定なし','申請終了日',to||'指定なし'],['学校ID','学校名','論文数','公開中','承認待ち','公開率'],...bySchool.map(s=>[s.id,s.name,s.total,s.published,s.pending,rate(s.published,s.total)]),[],['分野','公開論文数','公開論文内比率'],...distribution(published,'field').map(r=>[r.label,r.count,r.percent.toFixed(1)+'%']),[],['申請月','申請数','うち現在公開中'],...[...months].sort(([a],[b])=>a.localeCompare(b)).map(([m,n])=>[m,n.total,n.published])];const escape=(x:string|number)=>'"'+String(x).replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const url=URL.createObjectURL(new Blob(['\uFEFF'+cells.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='LTI-analytics.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const card=(label:string,value:string|number)=><div key={label} className="border rounded-xl bg-white p-5"><p className="text-xs text-gray-500">{label}</p><p className="text-2xl font-bold mt-2">{value}</p></div>;
 return <div className="space-y-6"><header className="flex flex-wrap gap-3 items-center"><h1 className="text-2xl font-bold flex-1">{page}</h1><button disabled={busy} className="border rounded-xl p-3" onClick={async()=>{setBusy(true);try{await reload();}finally{setBusy(false);}}}>{busy?'更新中…':'最新データに更新'}</button><button disabled={invalid} className="bg-indigo-600 text-white rounded-xl p-3 disabled:opacity-40" onClick={csv}>論文集計CSVを保存</button></header>
 <section className="bg-white border rounded-2xl p-5 space-y-3"><div className="flex flex-wrap gap-4"><label className="text-sm">学校<select value={school} onChange={e=>setSchool(e.target.value)} className="block border p-2 rounded-lg"><option value="">すべての学校</option>{[...schoolNames].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm">論文の申請日・開始<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="block border p-2 rounded-lg"/></label><label className="text-sm">終了<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="block border p-2 rounded-lg"/></label><button onClick={()=>{setSchool('');setFrom('');setTo('');}} className="text-sm underline">条件をリセット</button></div>{invalid&&<p role="alert" className="text-red-700">終了日は開始日以降にしてください。</p>}<p className="text-xs text-gray-500">保存済み論文を申請日で絞り込み、現在の公開状態を集計します。公開率＝公開中÷対象論文数。取り消して削除された申請は含みません。{unknown>0&&`日付不明${unknown}件は期間指定時に除外します。`}</p></section>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{card('対象論文数',selected.length)}{card('現在公開中',published.length)}{card('公開率',rate(published.length,selected.length))}{card('承認待ち',selected.filter(p=>p.status==='承認待ち').length)}</div>
 <div className="grid lg:grid-cols-2 gap-5"><PublishedFields papers={selected}/><section className="p-6 bg-white rounded-2xl border space-y-4"><h2 className="font-bold">公開状態の内訳</h2><Bars rows={distribution(selected,'status')}/><p className="text-sm">差し止め申請中：{published.filter(p=>p.withdrawalRequested).length}件</p></section></div>
 <section className="bg-white border rounded-2xl p-6 overflow-auto"><h2 className="font-bold mb-4">学校別の論文状況</h2><table className="w-full text-sm text-left"><thead><tr>{['学校','対象論文','公開中','承認待ち','公開率'].map(h=><th key={h} className="p-3 border-b">{h}</th>)}</tr></thead><tbody>{bySchool.map(s=><tr key={s.id}><td className="p-3"><button className="underline" onClick={()=>setSchool(s.id)}>{s.name}</button></td><td>{s.total}</td><td>{s.published}</td><td>{s.pending}</td><td>{rate(s.published,s.total)}</td></tr>)}</tbody></table>{!bySchool.length&&<p className="text-gray-500 py-4">学校データはありません。</p>}</section>
 <section className="bg-white border rounded-2xl p-6"><h2 className="font-bold mb-2">月別の申請状況</h2><p className="text-xs text-gray-500 mb-4">申請月ごとの件数です。「公開中」は現在の状態であり、その月に公開した件数ではありません。</p><div className="space-y-3">{[...months].sort(([a],[b])=>a.localeCompare(b)).map(([m,n])=><div key={m} className="grid grid-cols-[100px_1fr] gap-3 text-sm"><span>{m}</span><div><p>{n.total}件（うち現在公開中 {n.published}件）</p><div className="bg-gray-100 h-2 mt-1"><div className="bg-indigo-500 h-2" style={{width:`${100*n.total/Math.max(1,...[...months.values()].map(x=>x.total))}%`}}/></div></div></div>)}{!months.size&&<p className="text-sm text-gray-500">対象期間の申請はありません。</p>}</div></section>
 {page==='利用状況レポート'&&<section className="space-y-4"><h2 className="font-bold">学校の利用状況（現在の保存件数）</h2><p className="text-xs text-gray-500">学校の絞り込みのみ適用。上の論文申請期間は適用しません。ログイン回数・閲覧回数は未計測です。提出物は再提出回数ではなく課題と生徒の組み合わせで数えます。</p><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{card('利用可能な生徒',currentUsers.filter(p=>p.role==='student').length)}{card('利用可能な教師',currentUsers.filter(p=>p.role==='teacher').length)}{card('課題数',schoolRows.filter(r=>r.kind==='assignments').length)}{card('提出済みの課題回答',schoolRows.filter(r=>r.kind==='submissions'&&r.data.status==='提出済み').length)}{card('フィードバック件数',schoolRows.filter(r=>r.kind==='feedback').length)}{card('教材数',schoolRows.filter(r=>r.kind==='materials').length)}</div></section>}
 </div>;
}
