import type { Thesis } from './thesis-catalog';
export const fullTheses: Thesis[] = [
  {
    "key": "soken-c74c72df82543053",
    "title": "初期宇宙の観測量について",
    "authors": "中塚 洋佑",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2017,
    "kind": "bachelor",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol26/2/GradThesis_NH_%E8%A8%82%E6%AD%A3%EF%BC%92.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-2d0ee5d526de7761",
    "title": "時間反転対称な位相的場の理論",
    "authors": "折井 一歩",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2026,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol46/3/%E6%99%82%E9%96%93%E5%8F%8D%E8%BB%A2%E5%AF%BE%E7%A7%B0%E3%81%AA%E4%BD%8D%E7%9B%B8%E7%9A%84%E5%A0%B4%E3%81%AE%E7%90%86%E8%AB%96.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-b65837a9dcd8fdc2",
    "title": "4次元系でのテンソル繰り込み群手法の改良",
    "authors": "杉本 悠斗",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2025,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol44/3/250325-Sugimoto.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-a5f2090bd372f254",
    "title": "Jackiw-Teitelboim重力とランダム行列",
    "authors": "宮内 祐",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2024,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol42/5/JT_gravity_main.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-b3f09101a7a52f8d",
    "title": "アノマリーの数学的基礎から現象論的応用まで",
    "authors": "川平 将志",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2024,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol42/4/master_thesis4.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-e296ea4e4e5ee475",
    "title": "On Orbifolds in Closed Superstring Field Theory",
    "authors": "張 湘杭",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2024,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol42/3/thesis.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-0e3de29a3f46113f",
    "title": "SU(3)格子QCDを用いたDimensional Reduction ゲージにおける低次元化の解析",
    "authors": "當銘 啓",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2024,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol42/2/%E4%BF%AE%E5%A3%AB%E8%AB%96%E6%96%87_%E7%95%B6%E9%8A%98%E5%95%93.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-cadc89a01af67ee4",
    "title": "ニュートリノ振動における波束効果",
    "authors": "三谷 日姫",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2023,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol41/1/master_thesis.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-2bc64b11a7b93001",
    "title": "フラクトン系における場の理論と双対性",
    "authors": "島村 洲太朗",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2023,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol39/3/thesis_shimamura_final.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-0310c296af6c1568",
    "title": "MUonE 実験によるミューオン g － 2 を説明可能な U(1)μ－τ ゲージ ボソンの探索",
    "authors": "和田 淳太郎",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2022,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol36/3/%E4%BF%AE%E5%A3%AB%E8%AB%96%E6%96%87%E5%92%8C%E7%94%B0%E6%B7%B3%E5%A4%AA%E9%83%8E_%E6%9C%80%E7%B5%82%E8%AA%BF%E6%95%B4%E7%89%88.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-6fc97dfa4bd6fd89",
    "title": "SU(3)三角格子反強磁性体の非線形シグマ模型による解析",
    "authors": "高橋 樹",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2022,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol36/2/shuron5.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-1a167e838bbf4733",
    "title": "超弦理論のトーラスコンパクト化モデルによる素粒子標準模型のフレーバー構造の再現",
    "authors": "菊地 渉太",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2021,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol35/1/MT_draft_3.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-5d823246fbd848ef",
    "title": "Anomaly Inflow In Curved Space",
    "authors": "青木 匠門",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2021,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol34/2/Anomaly_Inflow_In_Curved_Space.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-f8d2ad64b2ad7e73",
    "title": "超弦理論のフラックスコンパクト化におけるコンパクト空間の幾何学とフレーバー構造",
    "authors": "内田 光",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2020,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol33/1/%E4%BF%AE%E5%A3%AB%E8%AB%96%E6%96%87_%E7%B4%A0%E7%B2%92%E5%AD%90%E7%A0%94%E7%A9%B6_%E5%86%85%E7%94%B0.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-cca5cce40bc08c7f",
    "title": "背景磁場を含む 6 次元理論における スカラー場の質量補正の相殺機構",
    "authors": "廣瀬 拓哉",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2020,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol32/3/masterthesis.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-1673ed0866caae9e",
    "title": "Double Field Theoryにおけるゲージ対称性と Lie亜代数対によるVaisman亜代数の構成",
    "authors": "森 遥",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2020,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol32/2/master_mori.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-61985610936d4942",
    "title": "局所ローレンツ対称性に基づく一般相対性理論の拡張",
    "authors": "宮脇 渉太",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2020,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol32/1/%E4%BF%AE%E8%AB%96-%E7%B4%A0%E7%B2%92%E5%AD%90%E8%AB%96%E7%A0%94%E7%A9%B6.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-451e50adcc9be91d",
    "title": "QCDにおけるクォークの閉じ込めとカイラル対称性の自発的破れの関係の研究",
    "authors": "土居 孝寛",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2014,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol17/5/doi.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-407d1e4e963b11a7",
    "title": "AdS/CFT対応に基づいたSchwinger効果の解析",
    "authors": "佐藤 芳紀",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2013,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol15/4/sato.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-3b3ee6df942f7682",
    "title": "Quantum Gravity -discrete vs. continuum-",
    "authors": "佐藤 勇貴",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2010,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol4/1/sato2.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "soken-c55c153c89700eab",
    "title": "カイラルランダム行列模型によるQCD相構造の研究",
    "authors": "佐野 崇",
    "university": "素粒子論研究（所属は本文参照）",
    "field": "物理・宇宙",
    "year": 2009,
    "kind": "master",
    "access": "full",
    "sourceUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/shuron.html",
    "documentUrl": "https://www2.yukawa.kyoto-u.ac.jp/~soken.editorial/sokendenshi/vol2/2/msthesis_sano.pdf",
    "checkedAt": "2026-09-09"
  }
];
