import {SavedInsightReveal} from './AIActivity';
import React,{useEffect,useState} from 'react';
import {ArrowLeft,FileText,Lightbulb,Eye,Bookmark,Quote,Check} from 'lucide-react';
import {PdfView} from './cloud';
import {ResearchEvaluation} from './ResearchEvaluation';
import type {ResearchAnalysis} from './research-ai';
import type {LibraryPaper} from './ResearchLibrary';
import {copyText,formatPaperCitation,loadPaperEngagement,recordPaperCitation,recordPaperView,togglePaperBookmark,type PaperEngagement} from './paper-engagement';
export function ResearchDetail({paper,onBack,showEvaluation=false,trackView=true}:{paper:LibraryPaper & {aiAnalysis?:ResearchAnalysis};onBack:()=>void;showEvaluation?:boolean;trackView?:boolean}){
 const result=paper.aiAnalysis;
 const [engagement,setEngagement]=useState<PaperEngagement>({views:0,citations:0,bookmarks:0});
 const [bookmarked,setBookmarked]=useState(false);
 const [engagementMessage,setEngagementMessage]=useState('');
 const [engagementBusy,setEngagementBusy]=useState(false);
 useEffect(()=>{let active=true;setEngagementMessage('');void (async()=>{try{if(trackView)await recordPaperView(paper.id);const loaded=await loadPaperEngagement([paper.id]);if(!active)return;setEngagement(loaded.metrics[String(paper.id)]||{views:0,citations:0,bookmarks:0});setBookmarked(loaded.bookmarked.has(String(paper.id)));}catch{}})();return()=>{active=false;};},[paper.id,trackView]);
 async function toggleBookmark(){if(engagementBusy)return;setEngagementBusy(true);setEngagementMessage('');try{const before=bookmarked;const next=await togglePaperBookmark(paper.id);setBookmarked(next);if(next!==before)setEngagement(v=>({...v,bookmarks:Math.max(0,v.bookmarks+(next?1:-1))}));setEngagementMessage(next?'ブックマークに保存しました。':'ブックマークを解除しました。');}catch{setEngagementMessage('ブックマークを更新できませんでした。');}finally{setEngagementBusy(false);}}
 async function cite(){if(engagementBusy)return;setEngagementBusy(true);setEngagementMessage('');try{await copyText(formatPaperCitation(paper));const citations=await recordPaperCitation(paper.id);setEngagement(v=>({...v,citations}));setEngagementMessage('引用情報をクリップボードにコピーしました。');}catch{setEngagementMessage('引用情報をコピーできませんでした。');}finally{setEngagementBusy(false);}}
 return <section className="space-y-5"><button type="button" onClick={onBack} className="flex items-center gap-2 text-sm text-slate-500 font-bold"><ArrowLeft className="w-4 h-4"/>論文一覧に戻る</button><div className="grid grid-cols-1 xl:grid-cols-[minmax(0,2.3fr)_minmax(300px,1fr)] gap-6 items-start"><article aria-label="著者の研究成果" className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="bg-slate-100 px-6 py-3 font-bold text-slate-800">著者の研究成果</div><header className="p-6 border-b space-y-4"><span className="text-xs font-bold bg-indigo-50 text-indigo-700 rounded px-2 py-1">{paper.field}</span><h2 className="text-2xl font-bold text-slate-900 leading-relaxed">{paper.title}</h2><div className="text-xs text-slate-500 space-y-1"><p>学校：{paper.schoolNameOverride?.trim()||paper.schoolName}</p><p>著者：{paper.author} / 担当：{paper.submittedByTeacherName||'未登録'}</p><p>公開日：{paper.publishedDate||paper.submittedDate} / {paper.fileName||'添付ファイルなし'}</p></div><div className="flex flex-wrap items-center gap-2 pt-1"><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600"><Eye className="w-4 h-4"/>{engagement.views} ビュー</span><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600"><Bookmark className="w-4 h-4"/>{engagement.bookmarks} ブックマーク</span><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600"><Quote className="w-4 h-4"/>{engagement.citations} 引用</span><button type="button" disabled={engagementBusy} onClick={()=>void toggleBookmark()} className={`rounded-xl border px-3 py-2 text-xs font-bold disabled:opacity-50 ${bookmarked?'border-emerald-600 bg-emerald-600 text-white':'border-slate-200 bg-white text-slate-700 hover:border-emerald-400'}`}>{bookmarked?<span className="inline-flex items-center gap-1"><Check className="w-4 h-4"/>保存済み</span>:<span className="inline-flex items-center gap-1"><Bookmark className="w-4 h-4"/>ブックマーク</span>}</button><button type="button" disabled={engagementBusy} onClick={()=>void cite()} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 hover:border-violet-400 disabled:opacity-50"><span className="inline-flex items-center gap-1"><Quote className="w-4 h-4"/>引用をコピー</span></button></div>{engagementMessage&&<p role="status" className="text-xs font-medium text-emerald-700">{engagementMessage}</p>}</header><div className="p-4">{paper.storagePath?<PdfView path={paper.storagePath}/>:<p className="p-6 text-sm text-slate-500">本文ファイルは未登録です。</p>}{paper.abstract&&<details className="p-4 text-sm" open={!paper.storagePath}><summary className="font-bold cursor-pointer">著者による概要</summary><p className="mt-3 whitespace-pre-wrap leading-relaxed text-slate-600">{paper.abstract}</p></details>}</div></article>
 <aside aria-label="LTIのAIによる参考情報" className="space-y-4 xl:sticky xl:top-4 bg-violet-50 border-2 border-violet-200 rounded-2xl p-4"><h2 className="font-bold text-violet-900">✨ AI Research Insight｜LTIのAIによる参考情報</h2><p className="text-xs leading-relaxed text-violet-800">以下はLTIのAIが生成した参考情報です。原論文の一部や著者の見解ではありません。要約は本文と照合し、継続研究の提案は未検証のアイデアとして扱ってください。</p><p className="text-xs text-slate-500">保存済みの解析結果を表示します。閲覧時のAI解析は行いません。要約・提案は本文と照らし合わせて確認してください。</p>
 <SavedInsightReveal key={String(paper.id)} enabled={!!result}>
 {showEvaluation&&result&&<ResearchEvaluation value={result.evaluation}/>} 
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-3"><h3 className="font-bold flex gap-2 items-center"><Lightbulb className="w-5 h-5 text-amber-500"/>この研究の着眼点<span className="ml-auto text-[10px] bg-amber-50 text-amber-700 rounded-full px-2 py-1">AI整理</span></h3><p className="text-xs text-slate-500">「なぜこのテーマに注目したのか」「どんな点を確かめたのか」を、分かりやすく紹介します。</p>{result?.summary.length?<p className="text-sm leading-relaxed text-slate-600">{result.summary[0]}</p>:<p className="text-sm text-slate-400">着眼点はまだ整理されていません。</p>}</section>
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-4"><h3 className="font-bold flex gap-2 items-center"><FileText className="w-5 h-5 text-emerald-600"/>研究から分かったこと<span className="ml-auto text-[10px] bg-emerald-50 text-emerald-700 rounded-full px-2 py-1">AI要約</span></h3><p className="text-xs text-slate-500">どのように調べ、何が見えてきたのかを整理します。専門用語には簡単な説明を添えます。</p>{result?.summary.length?<ul className="space-y-3">{result.summary.slice(1).map((s,i)=><li key={i} className="flex gap-2 text-sm leading-relaxed text-slate-600"><span className="text-emerald-600">●</span><span>{s}</span></li>)}</ul>:<p className="text-sm text-slate-400">内容はまだ整理されていません。</p>}</section>
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-4"><h3 className="font-bold flex gap-2 items-center"><Lightbulb className="w-5 h-5 text-violet-600"/>次につながる問い</h3><p className="text-xs text-slate-500">未検証のアイデアです。準備物や代替案を確認し、指導者と相談して計画しましょう。</p>{result?result.suggestions.map((s,i)=><div key={i} className="text-sm space-y-2 border-t border-slate-100 pt-3"><h4 className="font-bold text-emerald-800">{s.title}</h4><p className="text-slate-600 leading-relaxed whitespace-pre-wrap">{s.description}</p><div className="flex flex-wrap gap-1">{s.tags.map(t=><span key={t} className="text-[10px] bg-emerald-50 text-emerald-700 rounded px-2 py-1">{t}</span>)}</div></div>):<p className="text-sm text-slate-400">提案はまだ保存されていません。</p>}</section>
 {result&&<div className="text-xs text-slate-500 space-y-2"><p>解析範囲：{result.basis}</p><p>生成日時：{new Date(result.generatedAt).toLocaleString('ja-JP')}</p></div>}</SavedInsightReveal></aside></div></section>;
}
