import React,{useState} from 'react';
import {Search,Building2,CalendarDays,BookOpen,Leaf,Atom,Globe,FlaskConical,Bot,Users,FileText} from 'lucide-react';
export type LibraryPaper={id:number;title:string;schoolName:string;author:string;field:string;publishedDate:string;submittedDate:string;abstract?:string;storagePath?:string;fileName?:string;submittedByTeacherName:string;status:string};
const themes=[{match:/生物|生命/,Icon:Leaf,color:'bg-emerald-100 text-emerald-700'}, {match:/物理/,Icon:Atom,color:'bg-blue-100 text-blue-700'},{match:/地学|環境/,Icon:Globe,color:'bg-amber-100 text-amber-800'},{match:/化学/,Icon:FlaskConical,color:'bg-violet-100 text-violet-700'},{match:/物作|情報|工学/,Icon:Bot,color:'bg-cyan-100 text-cyan-700'},{match:/社会/,Icon:Users,color:'bg-rose-100 text-rose-700'}];
export function ResearchLibrary<T extends LibraryPaper>({papers,onOpen}:{papers:T[];onOpen:(p:T)=>void}){
 const [query,setQuery]=useState('');const [field,setField]=useState('すべて');const [sort,setSort]=useState('new');const [limit,setLimit]=useState(24);
 const published=papers.filter(p=>p.status==='公開中');const words=query.normalize('NFKC').toLowerCase().trim().split(/\s+/).filter(Boolean);
 const matched=published.filter(p=>words.every(w=>[p.title,p.author,p.schoolName,p.field,p.abstract].join(' ').normalize('NFKC').toLowerCase().includes(w)));
 const fields=[...new Set(published.map(p=>p.field).filter(Boolean))];
 const results=matched.filter(p=>field==='すべて'||p.field===field).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'ja'):String(b.publishedDate||b.submittedDate).localeCompare(String(a.publishedDate||a.submittedDate)));
 return <section className="space-y-6"><header className="space-y-2"><h2 className="text-2xl font-extrabold text-slate-900">みんなの論文ライブラリ</h2><p className="text-sm text-slate-500">高校生の探究論文を読み、研究の工夫や次のアイデアに出会いましょう。</p></header>
 <label className="relative block"><Search className="absolute left-4 top-3.5 w-5 h-5 text-slate-400"/><input aria-label="公開論文を検索" value={query} onChange={e=>{setQuery(e.target.value);setLimit(24);}} placeholder="タイトル・著者・学校名・分野で検索…" className="w-full border border-slate-200 bg-white rounded-2xl pl-12 pr-4 py-3 text-sm"/></label>
 <div className="flex flex-wrap items-center gap-2"><div className="flex flex-wrap gap-2 flex-1" role="group" aria-label="研究分野">{['すべて',...fields].map(f=><button type="button" key={f} aria-pressed={f===field} onClick={()=>{setField(f);setLimit(24);}} className={`rounded-full border px-4 py-2 text-sm font-bold ${f===field?'bg-emerald-600 border-emerald-600 text-white':'bg-white border-slate-200 text-slate-600'}`}>{f} <span className="opacity-70 ml-1">{f==='すべて'?matched.length:matched.filter(p=>p.field===f).length}</span></button>)}</div><select aria-label="論文の並び順" className="border rounded-xl px-3 py-2 bg-white text-sm" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">新着順</option><option value="title">タイトル順</option></select></div>
 <p role="status" className="text-xs text-slate-500">{results.length}件の公開論文</p>
 <div className="grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 gap-5">{results.slice(0,limit).map(p=>{const theme=themes.find(t=>t.match.test(p.field))||{Icon:BookOpen,color:'bg-slate-100 text-slate-600'};const Icon=theme.Icon;return <button type="button" key={p.id} onClick={()=>onOpen(p)} className="text-left bg-white rounded-2xl border border-slate-200 p-5 shadow-sm hover:shadow-md hover:border-emerald-300 transition-all group flex flex-col gap-4"><div className="flex gap-4"><div aria-hidden="true" className={`shrink-0 w-20 sm:w-24 h-32 rounded-xl flex flex-col items-center justify-center gap-3 ${theme.color}`}><Icon className="w-11 h-11"/><span className="text-[10px] font-bold tracking-widest">RESEARCH</span></div><div className="min-w-0 space-y-2"><span className={`inline-block rounded px-2 py-0.5 text-xs font-bold ${theme.color}`}>{p.field||'分野未設定'}</span><h3 className="text-sm font-bold text-slate-900 leading-relaxed line-clamp-3 group-hover:text-emerald-800">{p.title}</h3><p className="text-xs text-slate-500 leading-relaxed line-clamp-2">{p.abstract||'論文を開いて研究内容を読む'}</p></div></div><div className="space-y-2 mt-auto text-xs text-slate-500"><p className="flex gap-2 items-center"><Building2 className="w-4 h-4 shrink-0"/>{p.schoolName}</p><p>著者：{p.author}</p><div className="flex justify-between gap-2 border-t border-slate-100 pt-3"><span className="flex gap-1 items-center"><CalendarDays className="w-4 h-4"/>{p.publishedDate||p.submittedDate||'日付未登録'}</span><span className="flex gap-1 items-center text-emerald-700"><FileText className="w-4 h-4"/>{p.storagePath?'本文を読む':'概要を読む'}</span></div></div></button>;})}</div>
 {!results.length&&<p className="p-12 text-center border rounded-2xl bg-white text-sm text-slate-500">{published.length?'条件に一致する論文がありません。':'公開された論文はまだありません。'}</p>}{results.length>limit&&<button type="button" className="border rounded-xl px-5 py-2" onClick={()=>setLimit(limit+24)}>さらに表示</button>}</section>;
}
