import React from 'react';
import {ArrowLeft,FileText,Lightbulb} from 'lucide-react';
import {PdfView} from './cloud';
import type {ResearchAnalysis} from './research-ai';
import type {LibraryPaper} from './ResearchLibrary';
export function ResearchDetail({paper,onBack}:{paper:LibraryPaper & {aiAnalysis?:ResearchAnalysis};onBack:()=>void}){
 const result=paper.aiAnalysis;
 return <section className="space-y-5"><button type="button" onClick={onBack} className="flex items-center gap-2 text-sm text-slate-500 font-bold"><ArrowLeft className="w-4 h-4"/>論文一覧に戻る</button><div className="grid grid-cols-1 xl:grid-cols-[minmax(0,2.3fr)_minmax(300px,1fr)] gap-6 items-start"><article aria-label="著者の研究成果" className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="bg-slate-100 px-6 py-3 font-bold text-slate-800">著者の研究成果</div><header className="p-6 border-b space-y-3"><span className="text-xs font-bold bg-indigo-50 text-indigo-700 rounded px-2 py-1">{paper.field}</span><h2 className="text-2xl font-bold text-slate-900 leading-relaxed">{paper.title}</h2><div className="text-xs text-slate-500 space-y-1"><p>学校：{paper.schoolName}</p><p>著者：{paper.author} / 担当：{paper.submittedByTeacherName||'未登録'}</p><p>公開日：{paper.publishedDate||paper.submittedDate} / {paper.fileName||'添付ファイルなし'}</p></div></header><div className="p-4">{paper.storagePath?<PdfView path={paper.storagePath}/>:<p className="p-6 text-sm text-slate-500">本文ファイルは未登録です。</p>}{paper.abstract&&<details className="p-4 text-sm" open={!paper.storagePath}><summary className="font-bold cursor-pointer">著者による概要</summary><p className="mt-3 whitespace-pre-wrap leading-relaxed text-slate-600">{paper.abstract}</p></details>}</div></article>
 <aside aria-label="LTIのAIによる参考情報" className="space-y-4 xl:sticky xl:top-4 bg-violet-50 border-2 border-violet-200 rounded-2xl p-4"><h2 className="font-bold text-violet-900">✨ AI Research Insight｜LTIのAIによる参考情報</h2><p className="text-xs leading-relaxed text-violet-800">以下はLTIのAIが生成した参考情報です。原論文の一部や著者の見解ではありません。要約は本文と照合し、継続研究の提案は未検証のアイデアとして扱ってください。</p><p className="text-xs text-slate-500">保存済みの解析結果を表示します。閲覧時のAI解析は行いません。要約・提案は本文と照らし合わせて確認してください。</p>
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-4"><h3 className="font-bold flex gap-2 items-center"><FileText className="w-5 h-5 text-emerald-600"/>AIからの要点まとめ<span className="ml-auto text-[10px] bg-emerald-50 text-emerald-700 rounded-full px-2 py-1">AI要約</span></h3><p className="text-xs text-slate-500">研究の目的・方法・結果・限界を整理します。</p>{result?<ul className="space-y-3">{result.summary.map((s,i)=><li key={i} className="flex gap-2 text-sm leading-relaxed text-slate-600"><span className="text-emerald-600">●</span><span>{s}</span></li>)}</ul>:<p className="text-sm text-slate-400">要約はまだ生成されていません。</p>}</section>
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-4"><h3 className="font-bold flex gap-2 items-center"><Lightbulb className="w-5 h-5 text-emerald-600"/>継続研究のおすすめ</h3><p className="text-xs text-slate-500">未検証のアイデアです。指導者と相談して計画しましょう。</p>{result?result.suggestions.map((s,i)=><div key={i} className="text-sm space-y-2 border-t border-slate-100 pt-3"><h4 className="font-bold text-emerald-800">{s.title}</h4><p className="text-slate-600 leading-relaxed">{s.description}</p><div className="flex flex-wrap gap-1">{s.tags.map(t=><span key={t} className="text-[10px] bg-emerald-50 text-emerald-700 rounded px-2 py-1">{t}</span>)}</div></div>):<p className="text-sm text-slate-400">提案はまだ保存されていません。</p>}</section>
 {result&&<div className="text-xs text-slate-500 space-y-2"><p>解析範囲：{result.basis}</p><p>生成日時：{new Date(result.generatedAt).toLocaleString('ja-JP')}</p></div>}</aside></div></section>;
}
