import React,{useEffect,useState,useRef} from 'react';
import {ArrowLeft,FileText,Lightbulb,RotateCw} from 'lucide-react';
import {PdfView} from './cloud';
import {supabase} from './client';
import {analysisInput,invokeResearchAI,type ResearchAnalysis} from './research-ai';
import type {LibraryPaper} from './ResearchLibrary';
export function ResearchDetail({paper,onBack}:{paper:LibraryPaper;onBack:()=>void}){
 const [result,setResult]=useState<ResearchAnalysis|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const active=useRef<AbortController|null>(null);
 const run=async(force=false)=>{active.current?.abort();const controller=new AbortController();active.current=controller;setLoading(true);setError('');setResult(null);
 try{
  const {data:status,error:statusError}=await supabase.functions.invoke('research-ai',{body:{mode:'status'},signal:controller.signal});
  if(statusError)throw new Error('AI接続状態を確認できません。再試行してください。');
  if(!status?.configured)throw new Error('AI連携の設定待ちです。LTI運営がAPIキーを設定すると要約・提案を利用できます。');
  let input:Record<string,unknown>;
  if(paper.storagePath){const {data,error}=await supabase.storage.from('lti-documents').download(paper.storagePath);if(error||!data)throw new Error('原稿を取得できませんでした。');input=await analysisInput(data,paper.storagePath);}
  else {if(!paper.abstract||paper.abstract.trim().length<40)throw new Error('解析できる本文・概要が登録されていません。');input={text:paper.abstract,basis:'登録された概要のみ（本文未解析）'};}
  if(controller.signal.aborted)return;
  const response=await invokeResearchAI({mode:'analyze',title:paper.title,...input,force},controller.signal);if(active.current===controller&&!controller.signal.aborted)setResult(response);
 }catch(e){if(active.current===controller&&!controller.signal.aborted)setError(e instanceof Error?e.message:'解析できませんでした。');}finally{if(active.current===controller)setLoading(false);}};
 useEffect(()=>{void run();return()=>active.current?.abort();},[paper.id,paper.storagePath]);
 return <section className="space-y-5"><button type="button" onClick={onBack} className="flex items-center gap-2 text-sm text-slate-500 font-bold"><ArrowLeft className="w-4 h-4"/>論文一覧に戻る</button><div className="grid grid-cols-1 xl:grid-cols-[minmax(0,2.3fr)_minmax(300px,1fr)] gap-6 items-start"><article className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><header className="p-6 border-b space-y-3"><span className="text-xs font-bold bg-indigo-50 text-indigo-700 rounded px-2 py-1">{paper.field}</span><h2 className="text-2xl font-bold text-slate-900 leading-relaxed">{paper.title}</h2><div className="text-xs text-slate-500 space-y-1"><p>学校：{paper.schoolName}</p><p>著者：{paper.author} / 担当：{paper.submittedByTeacherName||'未登録'}</p><p>公開日：{paper.publishedDate||paper.submittedDate} / {paper.fileName||'添付ファイルなし'}</p></div></header><div className="p-4">{paper.storagePath?<PdfView path={paper.storagePath}/>:<p className="p-6 text-sm text-slate-500">本文ファイルは未登録です。</p>}{paper.abstract&&<details className="p-4 text-sm" open={!paper.storagePath}><summary className="font-bold cursor-pointer">著者による概要</summary><p className="mt-3 whitespace-pre-wrap leading-relaxed text-slate-600">{paper.abstract}</p></details>}</div></article>
 <aside className="space-y-4 xl:sticky xl:top-4"><p className="text-xs text-slate-500">原稿をAIに送信して解析します。要約・提案は本文と照らし合わせて確認してください。</p>
 {error&&<div role="alert" className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-sm text-amber-900 space-y-3"><p>{error}</p><button type="button" onClick={()=>void run(true)} className="underline flex gap-2 items-center"><RotateCw className="w-4 h-4"/>再試行</button></div>}
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-4"><h3 className="font-bold flex gap-2 items-center"><FileText className="w-5 h-5 text-emerald-600"/>AIからの要点まとめ<span className="ml-auto text-[10px] bg-emerald-50 text-emerald-700 rounded-full px-2 py-1">AI要約</span></h3><p className="text-xs text-slate-500">研究の目的・方法・結果・限界を整理します。</p>{loading?<p role="status" className="text-sm text-emerald-700 animate-pulse">原稿を解析しています…</p>:result?<ul className="space-y-3">{result.summary.map((s,i)=><li key={i} className="flex gap-2 text-sm leading-relaxed text-slate-600"><span className="text-emerald-600">●</span><span>{s}</span></li>)}</ul>:<p className="text-sm text-slate-400">要約はまだ生成されていません。</p>}</section>
 <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-4"><h3 className="font-bold flex gap-2 items-center"><Lightbulb className="w-5 h-5 text-emerald-600"/>継続研究のおすすめ</h3><p className="text-xs text-slate-500">未検証のアイデアです。指導者と相談して計画しましょう。</p>{result?result.suggestions.map((s,i)=><div key={i} className="text-sm space-y-2 border-t border-slate-100 pt-3"><h4 className="font-bold text-emerald-800">{s.title}</h4><p className="text-slate-600 leading-relaxed">{s.description}</p><div className="flex flex-wrap gap-1">{s.tags.map(t=><span key={t} className="text-[10px] bg-emerald-50 text-emerald-700 rounded px-2 py-1">{t}</span>)}</div></div>):<p className="text-sm text-slate-400">{loading?'要約とあわせて生成中です…':'提案はまだ生成されていません。'}</p>}</section>
 {result&&<div className="text-xs text-slate-500 space-y-2"><p>解析範囲：{result.basis}</p><p>生成日時：{new Date(result.generatedAt).toLocaleString('ja-JP')}</p><button disabled={loading} onClick={()=>void run(true)} className="underline">要約・提案を再生成</button></div>}</aside></div></section>;
}
