export type Thesis = { key:string; title:string; authors:string; university:string; field:string; year:number; kind:"bachelor"|"master"|"doctoral"; access:"title"|"summary"|"full"; sourceUrl:string; documentUrl?:string; checkedAt:string };
export const theses: Thesis[] = [
  {
    "key": "4bbb55a02a55a3a30fbc",
    "title": "高温高圧下におけるアコースティック・エミッション測定と能動的パルス透過法によるP波走時測定",
    "authors": "石井 裕介",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "3cfc1a8f99b27fba158b",
    "title": "愛媛県松山市中島に産するざくろ石を含む瀬戸内火山岩類",
    "authors": "泉田 義智",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "367e1b8f3b7e9bfffd5b",
    "title": "愛媛県西部、頃時鼻超苦鉄質岩体に伴うロジン岩",
    "authors": "岩谷 翔馬",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "5a2a038b7d1e48eab33b",
    "title": "イルメナイトとカンラン石の粘性率比 〜月マントルオーバーターンの解明に向けて〜",
    "authors": "江藤 羽生",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "732c3b18a8278028ffec",
    "title": "低エネルギーX線領域での XAFS 測定に向けたコニカルサポート型2段式ダイヤモンドアンビルセルの技術開発",
    "authors": "大西 黎",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "efe109c0801d4c5ca5da",
    "title": "現生サバ科魚類18種の骨格形態比較: 主上顎骨・歯骨・前鰓蓋骨・肩帯",
    "authors": "岡崎 いず美",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "175fe0241a46846eb3c2",
    "title": "ウニ殻形態のモデル化とその評価",
    "authors": "越智 巧己",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "5c13c7ca595fafff411c",
    "title": "CaSiO3・H2O 新奇高圧含水相の熱力学的安定性および弾性特性",
    "authors": "梶原 萌",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "65d39782446fa5f35cc8",
    "title": "高頻度 BGC-Argo 観測データを用いた短周期の混合層変動とそれに伴う表層への硝酸塩供給に関する研究",
    "authors": "加藤 翔",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "effc583d81eaa8617b30",
    "title": "放散虫 Saturnalidae 科の進化系統樹の再構築",
    "authors": "河本 倖志",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "ee4648553acbcdc19eb6",
    "title": "エンスタタイトコンドライト小惑星の形成と集積進化",
    "authors": "神林 勇和",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b2d0343288c49ec57c21",
    "title": "沖縄東方のフィリピン海より採取された鉄マンガンノジュールの内部構造と化学組成",
    "authors": "菊池 優希冶",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "e9feb0f1c8abd0c83ddd",
    "title": "豊後水道周辺海域の海面水温が2024年11月の松山市における大雨事例に及ぼした影響",
    "authors": "國金 美咲",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "31cd4b84b4c3798a2bdf",
    "title": "愛媛県四国中央市五良津に産する蛇紋岩と結晶片岩類",
    "authors": "窪田 遥",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "48007eadfbe8a2dffd9d",
    "title": "タイ北部の Chiang Muan 炭鉱から産出した中新世サイ科化石",
    "authors": "菅沼 智也",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "af8c06ee10227beb3c9e",
    "title": "2段式ダイヤモンドアンビルセル設計における単結晶ダイヤモンドの最適な加圧面の検証",
    "authors": "関根 荘生",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "53ffcec965d49605b481",
    "title": "現生放散虫の摂餌様式と殻成長の検討",
    "authors": "高田 透空",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "510060162f0c7a93d2c1",
    "title": "第四紀黒部川花崗岩のジルコン中メルト包有物研究",
    "authors": "田口 湧一",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "33b948cbd07919ff4f19",
    "title": "Subduction Channel モデルに基づく地殻物質の沈み込み量の見積もり",
    "authors": "伊達 璃子",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "bfd2f203529a50f50506",
    "title": "タイの中新統で産出した偶蹄類化石",
    "authors": "長田 豪丈",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "5b11292975947635b6a6",
    "title": "統計手法に基づく宇和海におけるカレニア赤潮発生日予測に関する研究",
    "authors": "橋本 元緯",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "1dd59f5bb38f2029d0a9",
    "title": "岩手県門地域北部北上帯大鳥ユニット産ジュラ紀中世前期放散虫化石群集の解析と Yamatoum 属の検討",
    "authors": "原 康太",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "371a6b1d6e9e011df5e8",
    "title": "大阪湾の海底コアを用いた微細マイクロプラスチック沈積量の推定",
    "authors": "日淺 美夢",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "a0bf66a1dea833963ca2",
    "title": "火星の熱的進化に与える発熱元素の再分配の影響: 火成活動を伴う2次元円環領域内マントル対流シミュレーションによる考察",
    "authors": "福田 竜大",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b919be4c0b80ee21c095",
    "title": "稍深発地震発生場の温度圧力条件下におけるカンラン石の引張変形実験とアコースティックエミッション測定に関する技術開発",
    "authors": "細川 泰雅",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "3ca4d03967a50dc26c18",
    "title": "稍深発地震発生場の温度圧力条件下におけるカンラン石の変形・破壊実験と広帯域型圧電トランスデューサを用いたアコースティックエミッションの測定",
    "authors": "松下 昌令",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "d7ec29e2853c5b152c8c",
    "title": "愛知県知多半島の中新統師崎層群から産出したサバ科魚類化石",
    "authors": "水野 誠也",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "c2793df060b035f6805f",
    "title": "モンゴル南東部の Shunkht から産出した前期漸新世の Amphicticeps (食肉目クマ下目) の化石",
    "authors": "宮内 愛奈",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "da13f781a5e39c0a0877",
    "title": "新潟県糸魚川市青海川地域に産出する listvenite の形成過程について",
    "authors": "榎田 一馬",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "effb9d28a26ad30ffbef",
    "title": "南半球アローロックス島における P/T 境界層状チャートの堆積相解析と層序再検討",
    "authors": "江濱 拓人",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "7b84da6eab2f8a7a6284",
    "title": "液体データを活用した高精度機械学習ポテンシャルの作成〜広い温度圧力領域における大規模分子動力学計算に向けて〜",
    "authors": "根来 匠",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "38d77168c5661bfd42f1",
    "title": "下部マントル条件下の MgO-NaAlO2 系の高温高圧相関係の解明",
    "authors": "早川 遼太郎",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "797eb800837ec4794788",
    "title": "外洋堆積物コアを用いた微細マイクロプラスチックの沈積量の推定",
    "authors": "森本 杏",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2025,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r07_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "aa0ca74e5d589dc15ddf",
    "title": "愛媛県梶島に産する斑れい岩類・ペグマタイト・電気石脈の形成〜サブソリダス下から熱水期における反応〜",
    "authors": "太田 一樹",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "d62518a331bcde08c68a",
    "title": "ニュージーランド北島 Arrow Rocks 島 Permian-Triassic 境界チャート層における PAHs 含有量分析と含有微化石の検討",
    "authors": "萩原 誉",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "91124b7958292b418ef9",
    "title": "トカラ海峡周辺における栄養塩添加に伴う低次生態系応答",
    "authors": "門田 雅仁",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "9299744830538cb04705",
    "title": "領家帯蒲野花崗閃緑岩の形成環境: ジルコンとメルト包有物からの制約",
    "authors": "川島 泰地",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "ec2d38896d7b24024e26",
    "title": "中生代白亜紀南半球高緯度帯の放散虫群集組成と殻形態の検討",
    "authors": "河野 駿輝",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "115b10a7d77fcd2cbce1",
    "title": "稍深発地震発生場の温度圧力条件下におけるカンラン石のその場観察変形・破壊実験と断層の空間分布観察",
    "authors": "久保田 哲矢",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "6d89e9cf0504d4a5b25f",
    "title": "Massive and foliated serpentinites from the Udonohana ultramafic body, Western Ehime Prefecture, Japan",
    "authors": "城口 結衣",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "02bd676b7b0e8e29fca3",
    "title": "網走湖堆積物中の DNA を用いた生物群集の長期変遷過程に関する研究",
    "authors": "須佐 周子",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "0e75aa57e6a56deec90e",
    "title": "Multituberculate mammals from the Upper Cretaceous Kuji and Himenoura groups, Japan",
    "authors": "世羅 拓真",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "be99e0d59a7ddf240b73",
    "title": "岩石天体内部の粘弾性変形と熱伝導の数値シミュレーションに基づく月の化石バルジの検討",
    "authors": "寺戸 聖菜",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "989f55e4f48e8605a415",
    "title": "西南日本内帯に産する花崗岩類の形成場の変化",
    "authors": "中橋 甲斐",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b616573a147607f3ffb8",
    "title": "広帯域型圧電トランスデューサを用いた高温高圧下でのアコーステッィク・エミッション測定のための技術開発",
    "authors": "宮川 大和",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "27ebee47eb859555b53b",
    "title": "豊後水道における急潮進入に対する低次生態系応答",
    "authors": "安藤 岬希",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "edc3cb19ff589c9c58e7",
    "title": "第一原理計算による超高圧下における CaCO3 と CO2 の結晶構造探索",
    "authors": "磯部 みのり",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b9defc811a5c848d0337",
    "title": "北海道苫前郡古丹別地域の上部白亜系層序",
    "authors": "伊藤 聖真",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f305cf4925c0b40bdcbf",
    "title": "第一原理計算による含水ブリッジマナイトの構造モデルと赤外スペクトル (First-principles calculation of the structural models and the infra-red spectra of hydrous bridgmanite)",
    "authors": "稲垣 喜久代",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "5936ce6c1510d82cbc75",
    "title": "巨大氷惑星内部条件における C-H-O 流体からのダイヤモンド生成実験",
    "authors": "上垣 朱以",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "a6c58ad89292b1a7f01d",
    "title": "Yin-Yang 3次元球殻マントル対流シミュレーションの流れ場を求める直接解法の開発",
    "authors": "上村 勇輔",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "ae40ef71f2121cd3b943",
    "title": "潮汐フロント周辺の流動構造に関する観測的研究",
    "authors": "梅若 亜理子",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "1e5f5f8d512fc004ec43",
    "title": "北海道小平地域の上部白亜系層序",
    "authors": "雲野 ひばり",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "0825584f31acbba3b4bb",
    "title": "糸魚川地域に産するひすい輝石岩と超苦鉄質岩類",
    "authors": "岡田 侑楽",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "4daa7fa47a6e9c0785a9",
    "title": "clinochrysotile と orthochrysotile の粉末 XRD 分析手法の検討と形成条件についての考察",
    "authors": "門屋 愛那",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "7958fcfbbad7ca76624f",
    "title": "モンゴル南東部の上部始新統 Ergilin Dzo 層から産出したカリコテリウム類 (哺乳綱奇蹄目) の化石",
    "authors": "仮谷 駿佑",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "0ad6c3664ba4d8800dd3",
    "title": "山陽帯山口県岩国市に分布する土生花崗岩質岩体のジルコン中メルト包有物研究",
    "authors": "熊谷 汐莉",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "0ba0217322298c42e4e5",
    "title": "GEMS 様物質の組織の再現を目的とした Mg-Si-O 系非晶質物質の水質変成実験",
    "authors": "斎藤 愛華",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "40670ff07f5c27daea59",
    "title": "高温高圧における水素化鉄中の Fe-Ni 相互拡散",
    "authors": "坂根 拓巳",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "fccfd5495f1b6f4e8000",
    "title": "火星核の上におけるメルトの存在と鉱物組成に関する実験的制約",
    "authors": "清水 綾太",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b1a53147f157cae3546e",
    "title": "海底コアを用いた東シナ海におけるマイクロプラスチック沈積量の推定",
    "authors": "新垣 ひなた",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "48b56640ef683cb1977a",
    "title": "含ネオジム釉薬によるフォトクロミズムを有する磁器の物質科学的研究",
    "authors": "千賀 大雅",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "13f17d28ff96b5749ae3",
    "title": "氷天体内部における H2O-NH3 系の相関系と圧縮挙動",
    "authors": "竹内 萌々子",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "07a274225cc54ac194ab",
    "title": "マダイ (Pagrus major) とクロダイ (Acanthopagrus schlegelii) の臼歯状歯の形態比較",
    "authors": "武田 優花",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "c7d7e544249e97faebb7",
    "title": "ブリッジマナイトの結晶構造 における Fe と Al の影響",
    "authors": "内藤 佑太",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "558e5d4c08bc2955fcfd",
    "title": "海洋モデルを用いた伊勢湾の海水交換に関する研究",
    "authors": "中島 隆之介",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "e480132dc179974c5af0",
    "title": "愛媛県宇和島市 高月山岩体に産する菫青石‐セカニナ石固溶体を含むゼノリスの記載鉱物学的研究",
    "authors": "西岡 陸",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "a1e6ddc8ff680c55a2a7",
    "title": "モンゴル上部始新統 Ergilin Dzo 層から産出した鳥類の上腕骨化石",
    "authors": "新田 樹生",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "50bd7ecd60702a07b56f",
    "title": "別府湾のマイワシにおける堆積物 DNA の分解に関する研究",
    "authors": "堀江 直人",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "40340acd184370886b89",
    "title": "多項式外挿による反復解法の初期値推定の高度化: マントル対流3次元シミュレーションの収束性強化に向けて",
    "authors": "水谷 颯人",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f689156a3b3355e9615e",
    "title": "糸魚川地域に産するデュモルチェライトおよび電気石",
    "authors": "森岡 鈴葉",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f2e062ae9773e1826d32",
    "title": "川井型マルチアンビル装置におけるアコースティック・エミッション測定の技術開発",
    "authors": "渡辺 翔太",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "fbdb090169d82ef4a6be",
    "title": "愛媛県西予市明浜地域における上部三畳系の放散虫化石層序の解明と Os 同位体比層序対比",
    "authors": "大城 響",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "158bc285f585f3bbfdd3",
    "title": "豊後水道北部の潮汐フロント周辺における低次生態系動態",
    "authors": "パティンゴ リュウ",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "aecac175ac9bd51c7b4b",
    "title": "高月山花崗岩質岩体に産する \"チャーノカイト様岩\" の岩石記載とジルコン中メルト包有物研究",
    "authors": "平松 義土",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2024,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r06_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "5886c821e3a39de0b5a1",
    "title": "Phase relation in a natural hydrous basalt under the lower mantle conditions",
    "authors": "石川 裕太",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "e508b6e9a72ed4c23a59",
    "title": "第一原理計算から予測されるケイ酸塩メルト中の鉄の電荷不均化反応〜マグマオーシャンにおける新たな鉄核分離メカニズムの提案〜",
    "authors": "北口 一志",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "14dc45b27e11286476d0",
    "title": "応力履歴依存レオロジーモデルを用いた2次元円環マントル対流シミュレーションによるプレートテクトニクス再現の試み",
    "authors": "田井東 大貴",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "06243c6613a3095454c9",
    "title": "ジルコンおよびメルト包有物を用いた花崗岩質マグマ固結過程の物理条件解析",
    "authors": "谷脇 由華",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "096045c78ae292a752d9",
    "title": "西部瀬戸内海豊後水道における海洋酸性化の時空間変動",
    "authors": "原 佑輔",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "9a27dac94edf6908cb9d",
    "title": "堆積物 DNA を用いたカタクチイワシのハプロタイプ組成変化の復元",
    "authors": "平橋 佑介",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "2a2d0ccf2be4914c3f29",
    "title": "愛媛県芸予諸島伯方島に産する交代性閃長岩類の岩石学的研究",
    "authors": "福井 堂子",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "fc82a7eb21810ba94c4e",
    "title": "石鎚コールドロンを形成したマグマ供給系の深度解析",
    "authors": "福田 圭一郎",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "2bd25d51a791fb056a3a",
    "title": "ローズクォーツ中のデュモルチェライト様インクルージョンと呈色の関係性",
    "authors": "札元 颯人",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "967b5ccc7d7db4a0641e",
    "title": "Deformation of metastable olivine under pressure-temperature conditions of deep subducted slabs",
    "authors": "松田 光平",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "1ac616e5a5360f6251f3",
    "title": "北海道留萌郡小平町から産出した束柱類の上腕骨の化石",
    "authors": "三藤 万琳",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "670a0793221b8f946aaa",
    "title": "第一原理多配置サンプリング法を用いた Phase D と Li2ZrF6 型 SiO2との固溶体形成に関する統計力学モデル",
    "authors": "中川 采音",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "master",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_m",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "50d68cbd4b9248cacb3a",
    "title": "酸化的な微惑星マグマの窒素溶解度およびその分子種に関する実験的研究",
    "authors": "秋元 拓斗",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "894089f72fb9066f191d",
    "title": "月マントル組成直方輝石多結晶体の高圧高温下弾性波速度測定",
    "authors": "井上 義洋",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "56365230597e3c6fc44b",
    "title": "山陰帯島根県雲南地域に分布する大東花崗閃緑岩のジルコン中メルト包有物研究",
    "authors": "居平 千穂",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b0e53ced05ba5f820acb",
    "title": "モンゴル南東部 Khoer Dzan の上部始新統 Ergilin Dzo 層から産出した鳥類の大腿骨化石",
    "authors": "岩本 凜哉",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "48f5112e19ee08ab80c5",
    "title": "北極域ボーフォート海の基礎生産の変動",
    "authors": "尾上 遥",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "48d871a4da124b7e148a",
    "title": "愛媛県東温市表川流域の中新統久万層群から産出する植物化石",
    "authors": "工藤 翔",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f6b57c1990413f5432e9",
    "title": "愛媛県東赤石山芋野岩体にみられる Fe-Ni-O-S-As 系鉱物と蛇紋岩化作用の関係",
    "authors": "国吉 真斗",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "159dead77232ee945b4c",
    "title": "愛媛県上島町魚島に産するバラ石英の鉱物学的研究",
    "authors": "坂井 翔真",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "181bc66ce359ee2e3d2a",
    "title": "(Mg,Fe)SiO3メルトにおける鉄価数のメルト構造による制約",
    "authors": "櫻原 瑞穂",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "e500f1be8394578fe54a",
    "title": "愛媛県松山平野の上部白亜系和泉層群産ウニ化石の検討",
    "authors": "炭 元裕",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "6971636b3969aa375349",
    "title": "愛媛県四国中央市浦山川に産するリスウェナイト及び蛇紋岩",
    "authors": "髙垣 光",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "9167b67b1593c4cd535f",
    "title": "愛媛県松山市道後姫塚の上部白亜系和泉層群産 Squalicorax 属 (サメ類) の化石",
    "authors": "豊 大翔",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "a4de9ffc7a311508d92d",
    "title": "高圧下での酸化バリウムの相同定および状態方程式決定",
    "authors": "中村 悟",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f9e119794716c521e7bb",
    "title": "鹿児島県種子島の中新統茎永層群大崎層から産出したサイ類の椎骨化石",
    "authors": "長谷川 和紀",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "4cbc4a7ce954597c3d70",
    "title": "プレート沈み込み帯における熱・流れ構造の3次元シミュレーションモデルの開発",
    "authors": "羽藤 航周",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "a1dc465ba8ac85659bdc",
    "title": "適応的観点から見たアンモナイト性比の理論的解釈",
    "authors": "日山 義弥",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "15382a902bbbb5f950a7",
    "title": "ケニアの上部中新統ナカリ層から産出したホソマングースの化石",
    "authors": "兵頭 吏貴",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "9b519f8c823139d6ac7a",
    "title": "愛媛県西予市三瓶町蔵貫地区の鳥巣式石灰岩から産出した大型巻貝化石の検討",
    "authors": "平岡 美侑",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f6d2dc6fdda1cca75b72",
    "title": "2次元円環状モデルによるスーパー地球のマントル対流シミュレーション: 惑星サイズと内部発熱の効果",
    "authors": "藤森 乙瑛",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "0b14353a2f49c265de5f",
    "title": "ノリを含めた海洋低次生態系モデルの開発",
    "authors": "細川 琉平",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "ca5010f5716450f9d38c",
    "title": "海洋モデルの高度化がもらたす四国周辺の沿岸領域の再現性の研究",
    "authors": "宮内 音寧",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "59c1e63ef87c1e7eef7b",
    "title": "愛媛県東温市の中部中新統石鎚層群黒森峠層の岩石学的研究",
    "authors": "宮本 真愛",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "f8d393d15fb09afe4227",
    "title": "幼年殻の構成から見たアンモナイトの生活戦略とその時代的変遷",
    "authors": "森 柊斗",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "bf869c8d0b0cfc80c758",
    "title": "東シナ海の低次生態系動態観測と解析",
    "authors": "山岡 昂平",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "8bbae75d69dc740e10cb",
    "title": "豊後水道における急潮に伴う生態系応答に関する研究",
    "authors": "山下 碧斗",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "7fea18e18dace76f9a7c",
    "title": "四国西予明浜に確認されるトリアス/ジュラ(T/J)系境界における放散虫化石層序",
    "authors": "山林 時也",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "b593c0b7ad023f536242",
    "title": "高知県柏島近海黒潮表層の現生放散虫群集組成と内殻骨格成長の検討",
    "authors": "山本 健太",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "ecd14c40ac16daccd520",
    "title": "堆積物 DNA を用いた瀬戸内海の主要な動物プランクトン Paracalanus parvus の長期動態復元に関する研究",
    "authors": "横溝 壮真",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "e17d1bc47ca0474739be",
    "title": "愛媛県新居浜市保土野の高温型蛇紋岩の組織形成",
    "authors": "和田 姫名乃",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "c48f5be1c733c6a86228",
    "title": "異常巻きアンモナイト Nipponites の謎〜生息姿勢調節仮説の秘密〜",
    "authors": "四宮 七瀬",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "6361147f9f8d52c04b92",
    "title": "領家帯柳井地域木部花崗岩の全岩・メルト化学組成を用いた、マグマ分離・固結深度解析",
    "authors": "舛田 奏大",
    "university": "愛媛大学",
    "field": "地学・環境",
    "year": 2023,
    "kind": "bachelor",
    "access": "title",
    "sourceUrl": "https://earth.sci.ehime-u.ac.jp/articlelist.html#r05_b",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "waseda-arai-2025",
    "title": "トリルチル型CrTa₂O₆の作製と物性",
    "authors": "荒井 理沙",
    "university": "早稲田大学",
    "field": "物理・物性",
    "year": 2025,
    "kind": "bachelor",
    "access": "summary",
    "sourceUrl": "https://katsuf.w.waseda.jp/lab/sotu.htm",
    "documentUrl": "https://katsuf.w.waseda.jp/lab/sotu_shu_ron/sotu_arai.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "waseda-ikenoya-2025",
    "title": "Yb₁₋ₓCaₓTiO₃の軌道-スピン相互作用",
    "authors": "池谷 陽太郎",
    "university": "早稲田大学",
    "field": "物理・物性",
    "year": 2025,
    "kind": "bachelor",
    "access": "summary",
    "sourceUrl": "https://katsuf.w.waseda.jp/lab/sotu.htm",
    "documentUrl": "https://katsuf.w.waseda.jp/lab/sotu_shu_ron/sotu_ikenoya.pdf",
    "checkedAt": "2026-09-09"
  },
  {
    "key": "waseda-ikeda-2025",
    "title": "Sm₁₋ₓGdₓTiO₃の軌道-スピン相互作用",
    "authors": "池田 凱",
    "university": "早稲田大学",
    "field": "物理・物性",
    "year": 2025,
    "kind": "master",
    "access": "summary",
    "sourceUrl": "https://katsuf.w.waseda.jp/lab/sotu.htm",
    "documentUrl": "https://katsuf.w.waseda.jp/lab/sotu_shu_ron/shu_ron/shu_ikeda_k.pdf",
    "checkedAt": "2026-09-09"
  }
];
