import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFileSync,writeFileSync,unlinkSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import React from 'react';

const result=await build({entryPoints:['ResearchLibrary.tsx'],bundle:true,platform:'node',format:'esm',write:false,external:['react','react-dom','lucide-react']});
const path=new URL('../.admin-paper-library-test.mjs',import.meta.url);
writeFileSync(path,result.outputFiles[0].text);
try{
 const {ResearchLibrary}=await import(path.href);
 const makePaper=(id,status)=>({id,title:`研究論文${id}`,schoolName:'登録学校名',schoolNameOverride:id===1?'運営が編集した学校名':null,author:'研究者',field:'物理',publishedDate:'',submittedDate:'2026-09-21',submittedByTeacherName:'先生',status});
 const papers=[makePaper(1,'公開中'),makePaper(2,'承認待ち'),makePaper(3,'公開停止')];
 const publicHtml=renderToStaticMarkup(React.createElement(ResearchLibrary,{papers,onOpen:()=>{}}));
 assert.match(publicHtml,/1件の公開論文/);
 assert.match(publicHtml,/研究論文1/);
 assert.doesNotMatch(publicHtml,/研究論文2|研究論文3/);
 assert.match(publicHtml,/運営が編集した学校名/);
 const adminHtml=renderToStaticMarkup(React.createElement(ResearchLibrary,{papers,onOpen:()=>{},includeUnpublished:true}));
 assert.match(adminHtml,/3件の論文/);
 assert.match(adminHtml,/研究論文2/);
 assert.match(adminHtml,/研究論文3/);
 assert.match(adminHtml,/承認待ち/);
 assert.match(adminHtml,/公開停止/);
 const adminSource=readFileSync(new URL('../AdminResearchLibrary.tsx',import.meta.url),'utf8');
 assert.match(adminSource,/const allRows=cloud\.rows\.filter\(r=>r\.kind==='papers'\)/);
 assert.match(adminSource,/activeRows=allRows\.filter\(r=>r\.data\.status!=='公開停止'\)/);
 assert.match(adminSource,/archivedRows=allRows\.filter\(r=>r\.data\.status==='公開停止'\)/);
 assert.match(adminSource,/section==='archive'\?archivedRows:activeRows/);
 assert.match(adminSource,/schoolNameOverride:/);
 assert.match(adminSource,/version,data/);
 assert.match(adminSource,/showEvaluation/);
 assert.match(adminSource,/5観点評価を生成/);
 assert.match(adminSource,/prepareResearch/);
 assert.match(adminSource,/async function unpublish\(\)/);
 assert.match(adminSource,/paper\?\.status!=='公開中'/);
 assert.match(adminSource,/status:'公開停止'/);
 assert.match(adminSource,/非公開にする/);
 assert.match(adminSource,/アーカイブへ移動しました/);
 assert.match(adminSource,/async function restore\(\)/);
 assert.match(adminSource,/status:'公開中'/);
 assert.match(adminSource,/公開に戻す/);
 assert.match(adminSource,/アーカイブ/);
 assert.match(adminSource,/lti_save_records/);
 const librarySource=readFileSync(new URL('../ResearchLibrary.tsx',import.meta.url),'utf8');
 assert.match(librarySource,/mathematics\.svg/);
 assert.match(librarySource,/medical\.svg/);
 assert.match(librarySource,/other\.svg/);
 assert.match(librarySource,/match:\/数学\//);
 assert.match(librarySource,/match:\/医療\|健康\//);
 assert.match(librarySource,/match:\/その他\//);
 assert.doesNotMatch(librarySource,/AI生成イメージ/);
 assert.doesNotMatch(librarySource,/AI生成・実際の研究写真ではありません/);
 assert.match(librarySource,/md:grid-cols-2 xl:grid-cols-3/);
 assert.match(librarySource,/gap-4/);
 assert.match(librarySource,/useState\('random'\)/);
 assert.match(librarySource,/sort==='random'/);
 assert.match(librarySource,/<option value="random">ランダム<\/option>/);
 assert.match(librarySource,/Math\.random\(\)/);
 assert.match(librarySource,/totalEvaluation/);
 assert.match(librarySource,/sort==='evaluation'/);
 assert.match(librarySource,/総合評価順/);
 assert.match(librarySource,/bTotal-aTotal/);
 assert.match(librarySource,/items\.length!==5/);
 assert.match(librarySource,/heading='みんなの論文ライブラリ'/);
 assert.match(librarySource,/countLabel/);
 assert.match(librarySource,/emptyText/);
 const detailSource=readFileSync(new URL('../ResearchDetail.tsx',import.meta.url),'utf8');
 assert.match(detailSource,/ResearchEvaluation/);
 const evaluationSource=readFileSync(new URL('../ResearchEvaluation.tsx',import.meta.url),'utf8');
 assert.match(evaluationSource,/着眼点・独創性/);
 assert.match(evaluationSource,/高校生ならではの柔軟な発想/);
 assert.match(detailSource,/result\?\.evaluation&&<div[^>]*><ResearchEvaluation value=\{result\.evaluation\} showChart=\{showEvaluation\} showScores=\{showEvaluation\}/);
 assert.match(detailSource,/大きく表示/);
 assert.match(detailSource,/AI Research Insight フルスクリーン表示/);
 assert.match(detailSource,/LTI AI RESEARCH INSIGHT/);
 assert.match(detailSource,/z-\[999\]/);
 assert.match(detailSource,/max-w-5xl/);
 assert.match(detailSource,/text-\[15px\] leading-7/);
 assert.match(detailSource,/document\.body\.style\.overflow='hidden'/);
 assert.match(detailSource,/leading-6 text-violet-900/);
 assert.match(detailSource,/<InsightBody expanded\/>/);
 assert.match(detailSource,/xl:grid-cols-\[minmax\(0,1\.65fr\)_minmax\(360px,0\.8fr\)\]/);
 assert.doesNotMatch(detailSource,/xl:grid-cols-\[minmax\(0,1\.4fr\)_minmax\(440px,1fr\)\]/);
 assert.match(evaluationSource,/showChart=true/);
 assert.match(evaluationSource,/showScores=true/);
 assert.match(evaluationSource,/\{showChart&&<>/);
 assert.match(evaluationSource,/showScores&&<p/);
 assert.match(evaluationSource,/:showScores\?<span/);
 assert.match(detailSource,/showScores=\{showEvaluation\}/);
 assert.match(evaluationSource,/評価理由・良い点/);
 assert.match(evaluationSource,/本文の根拠（ページ・節など）/);
 assert.match(evaluationSource,/さらに確かめたい点/);
 assert.match(evaluationSource,/v\[k\]\?\.trim\(\)\|\|'記載なし'/); const evaluationPosition=detailSource.indexOf('result?.evaluation&&<div');
 const suggestionsPosition=detailSource.indexOf('次につながる問い');
 assert(evaluationPosition>suggestionsPosition);
 assert.match(librarySource,/loadPaperEngagement/);
 assert.match(librarySource,/bookmarksOnly/);
 assert.match(librarySource,/ブックマーク/);
 assert.match(librarySource,/engagement\.views/);
 assert.match(librarySource,/engagement\.bookmarks/);
 assert.match(librarySource,/engagement\.citations/);
 assert.match(detailSource,/recordPaperView/);
 assert.match(detailSource,/togglePaperBookmark/);
 assert.match(detailSource,/recordPaperCitation/);
 assert.match(detailSource,/引用をコピー/);
 assert.match(detailSource,/ブックマーク/);
 assert.match(adminSource,/trackView=\{false\}/);
 const engagementSource=readFileSync(new URL('../paper-engagement.ts',import.meta.url),'utf8');
 assert.match(engagementSource,/lti_paper_engagement_counts/);
 assert.match(engagementSource,/lti_my_paper_bookmarks/);
 assert.match(engagementSource,/lti_toggle_paper_bookmark/);
 assert.match(engagementSource,/lti_record_paper_view/);
 assert.match(engagementSource,/lti_record_paper_citation/);
 assert.match(engagementSource,/formatPaperCitation/);
 assert.doesNotMatch(detailSource,/なぜこのテーマに注目したのか/);
 assert.doesNotMatch(detailSource,/どのように調べ、何が見えてきたのか/);
 const appSource=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');
const configSource=readFileSync(new URL('../supabase-config.ts',import.meta.url),'utf8');
const cloudSourceForEnv=readFileSync(new URL('../cloud.tsx',import.meta.url),'utf8');

 assert.match(appSource,/生徒・教員に配信している内容を運営側でも確認できます/);
 assert.match(appSource,/お知らせ管理を開く/);
 assert.match(appSource,/公式・申込URL/);
 assert.match(appSource,/詳細・申込ページ/);
 assert.match(appSource,/url\?: string/);
 assert.match(appSource,/const formatDisplayDateTime/);
 assert.match(appSource,/timeZone: 'Asia\/Tokyo'/);
 assert.match(appSource,/formatDisplayDateTime\(sub\.submittedAt\)/);
 assert.match(appSource,/name: '課題管理'/);
 assert.match(appSource,/assignmentStudentQuery/);
 assert.match(appSource,/attachmentPath\?: string/);
 assert.match(appSource,/attachmentName\?: string/);
 assert.match(appSource,/newAssignAttachment/);
 assert.match(appSource,/attachmentPath = await uploadPdf\(newAssignAttachment/);
 assert.match(appSource,/先生からの添付資料/);
 assert.match(appSource,/Supabase Storageに保存され、アプリ更新では消えません/);
 assert.match(configSource,/bvjjnzhhxieyxkeorurb/);
 assert.match(configSource,/ozmulwqzybhiekmolvyk/);
 assert.match(configSource,/APP_ENV: 'production' \| 'staging'/);
 assert.match(configSource,/PROD_HOSTS/);
 assert.match(cloudSourceForEnv,/STAGING \/ 試験環境/);
 assert.match(appSource,/placeholder="生徒名で検索（クラス・出席番号でも検索できます）"/);
 assert.match(appSource,/filteredSubmittedList/);
 assert.match(appSource,/filteredUnsubmittedList/);
 assert.match(appSource,/expandedSubmissionStudentId/);
 assert.match(appSource,/aria-expanded=\{expandedSubmissionStudentId===student\.id\}/);
 assert.match(appSource,/expandedSubmissionStudentId===student\.id&&<div/);
 assert.match(appSource,/setExpandedSubmissionStudentId\(current=>current===student\.id\?null:student\.id\)/);
 assert.match(appSource,/teacherFeatureTab=\(tab:string\)=>tab==='課題管理'\?'進捗管理':tab/);
 assert.match(appSource,/currentTab === '課題管理'/);
 assert.doesNotMatch(appSource,/currentTab === '進捗管理'/);
 assert.match(appSource,/setProgressSelectedAssignId\(assign\.id\);setExpandedSubmissionStudentId\(null\);setCurrentTab\('課題管理'\)/);
 assert.match(appSource,/aria-label="課題を編集"/);
 assert.match(appSource,/aria-label="課題を削除"/);
 assert.match(appSource,/showPicker\?\.\(\)/);
 assert.match(appSource,/font-mono cursor-pointer/);
 assert.match(appSource,/出席番号 \{\(student as any\)\.attendance_number \?\? "未設定"\}/);
 assert.match(appSource,/ファイルだけで一括申請/);
 assert.match(appSource,/handleTeacherBatchSubmitPapers/);
 assert.match(appSource,/multiple/);
 assert.match(appSource,/field: '未分類'/);
 assert.match(appSource,/title: file\.name\.replace/);
 assert.doesNotMatch(appSource,/最大ファイルサイズ: 50MB/);
 assert.doesNotMatch(appSource,/1ファイル50MBまで/);
 const uploadSource=readFileSync(new URL('../document-upload.ts',import.meta.url),'utf8');
 assert.doesNotMatch(uploadSource,/MAX_DOCUMENT_BYTES|50MB以内/);
 assert.match(uploadSource,/file\.size<=6\*1024\*1024/);
 assert.match(uploadSource,/tus-js-client/);
 const researchAiSource=readFileSync(new URL('../research-ai.ts',import.meta.url),'utf8');
 assert.doesNotMatch(researchAiSource,/原本は50MB以下|file\.size>50\*1024\*1024/);

 const cloudSource=readFileSync(new URL('../cloud.tsx',import.meta.url),'utf8');
 assert.match(cloudSource,/https:\/\/lti-explore-six\.vercel\.app\/\?flow=recovery/);
 assert.match(cloudSource,/function PdfPageCanvas/);
 assert.match(cloudSource,/function PdfFullscreenViewer/);
 assert.match(cloudSource,/LTI RESEARCH VIEWER/);
 assert.match(cloudSource,/aria-label="論文PDF 全画面ビューア"/);
 assert.match(cloudSource,/e\.key==='ArrowLeft'/);
 assert.match(cloudSource,/e\.key==='ArrowRight'/);
 assert.match(cloudSource,/Array\.from\(\{length:pages\}/);
 assert.match(cloudSource,/PdfPageCanvas key=\{pageNumber\}/);
 assert.match(cloudSource,/スクロールで全ページを連続閲覧/);
 assert.match(cloudSource,/pdf-page-\$\{pageNumber\}/);
 assert.match(cloudSource,/scrollIntoView/);
 assert.match(cloudSource,/Math\.min\(Math\.max\(window\.devicePixelRatio\|\|1,2\),2\.5\)/);
 assert.match(cloudSource,/e\.key==='Escape'/);
 assert.match(cloudSource,/pdfjs-dist/);
 assert.match(cloudSource,/bg-slate-950 text-white flex flex-col/);
 assert.doesNotMatch(cloudSource,/fixed inset-0 z-\[110\] bg-white p-4 overflow-auto/);
 assert.match(detailSource,/label=\{paper\.fileName\|\|paper\.title\}/);
 assert.doesNotMatch(cloudSource,/lti-explore-lab-to-impact\.vercel\.app\/\?flow=recovery/);
 console.log('PASS: admin library separates hidden papers into archive; public library only shows published papers');
}finally{unlinkSync(path);}
