import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFileSync,writeFileSync,unlinkSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import React from 'react';

const result=await build({entryPoints:['ResearchLibrary.tsx'],bundle:true,platform:'node',format:'esm',write:false,external:['react','react-dom','lucide-react']});
const path=new URL('../.admin-paper-library-test.mjs',import.meta.url);
writeFileSync(path,result.outputFiles[0].text);
try{
 const {ResearchLibrary}=await import(path.href);
 const makePaper=(id,status)=>({id,title:`研究論文${id}`,schoolName:'登録学校名',schoolNameOverride:id===1?'運営が編集した学校名':null,author:'研究者',field:'物理',publishedDate:'',submittedDate:'2026-09-21',submittedByTeacherName:'先生',status});
 const papers=[makePaper(1,'公開中'),makePaper(2,'承認待ち'),makePaper(3,'公開停止')];
 const publicHtml=renderToStaticMarkup(React.createElement(ResearchLibrary,{papers,onOpen:()=>{}}));
 assert.match(publicHtml,/1件の公開論文/);
 assert.match(publicHtml,/研究論文1/);
 assert.doesNotMatch(publicHtml,/研究論文2|研究論文3/);
 assert.match(publicHtml,/運営が編集した学校名/);
 const adminHtml=renderToStaticMarkup(React.createElement(ResearchLibrary,{papers,onOpen:()=>{},includeUnpublished:true}));
 assert.match(adminHtml,/3件の論文/);
 assert.match(adminHtml,/研究論文2/);
 assert.match(adminHtml,/研究論文3/);
 assert.match(adminHtml,/承認待ち/);
 assert.match(adminHtml,/公開停止/);
 const adminSource=readFileSync(new URL('../AdminResearchLibrary.tsx',import.meta.url),'utf8');
 assert.match(adminSource,/const allRows=cloud\.rows\.filter\(r=>r\.kind==='papers'\)/);
 assert.match(adminSource,/activeRows=allRows\.filter\(r=>r\.data\.status!=='公開停止'\)/);
 assert.match(adminSource,/archivedRows=allRows\.filter\(r=>r\.data\.status==='公開停止'\)/);
 assert.match(adminSource,/section==='archive'\?archivedRows:activeRows/);
 assert.match(adminSource,/schoolNameOverride:/);
 assert.match(adminSource,/version,data/);
 assert.match(adminSource,/showEvaluation/);
 assert.match(adminSource,/5観点評価を生成/);
 assert.match(adminSource,/prepareResearch/);
 assert.match(adminSource,/async function unpublish\(\)/);
 assert.match(adminSource,/paper\?\.status!=='公開中'/);
 assert.match(adminSource,/status:'公開停止'/);
 assert.match(adminSource,/非公開にする/);
 assert.match(adminSource,/アーカイブへ移動しました/);
 assert.match(adminSource,/async function restore\(\)/);
 assert.match(adminSource,/status:'公開中'/);
 assert.match(adminSource,/公開に戻す/);
 assert.match(adminSource,/アーカイブ/);
 assert.match(adminSource,/lti_save_records/);
 const librarySource=readFileSync(new URL('../ResearchLibrary.tsx',import.meta.url),'utf8');
 assert.match(librarySource,/mathematics\.svg/);
 assert.match(librarySource,/medical\.svg/);
 assert.match(librarySource,/other\.svg/);
 assert.match(librarySource,/match:\/数学\//);
 assert.match(librarySource,/match:\/医療\|健康\//);
 assert.match(librarySource,/match:\/その他\//);
 assert.doesNotMatch(librarySource,/AI生成イメージ/);
 assert.doesNotMatch(librarySource,/AI生成・実際の研究写真ではありません/);
 assert.match(librarySource,/md:grid-cols-2 xl:grid-cols-3/);
 assert.match(librarySource,/gap-4/);
 assert.match(librarySource,/useState\(includeUnpublished\?'new':'random'\)/);
 assert.match(librarySource,/sort==='random'/);
 assert.match(librarySource,/<option value="random">ランダム<\/option>/);
 assert.match(librarySource,/Math\.random\(\)/);
 assert.match(librarySource,/heading='みんなの論文ライブラリ'/);
 assert.match(librarySource,/countLabel/);
 assert.match(librarySource,/emptyText/);
 const detailSource=readFileSync(new URL('../ResearchDetail.tsx',import.meta.url),'utf8');
 assert.match(detailSource,/ResearchEvaluation/);
 const evaluationSource=readFileSync(new URL('../ResearchEvaluation.tsx',import.meta.url),'utf8');
 assert.match(evaluationSource,/着眼点・独創性/);
 assert.match(evaluationSource,/高校生ならではの柔軟な発想/);
 assert.match(detailSource,/showEvaluation&&result&&<ResearchEvaluation/);
 assert.match(librarySource,/loadPaperEngagement/);
 assert.match(librarySource,/bookmarksOnly/);
 assert.match(librarySource,/ブックマーク/);
 assert.match(librarySource,/engagement\.views/);
 assert.match(librarySource,/engagement\.bookmarks/);
 assert.match(librarySource,/engagement\.citations/);
 assert.match(detailSource,/recordPaperView/);
 assert.match(detailSource,/togglePaperBookmark/);
 assert.match(detailSource,/recordPaperCitation/);
 assert.match(detailSource,/引用をコピー/);
 assert.match(detailSource,/ブックマーク/);
 assert.match(adminSource,/trackView=\{false\}/);
 const engagementSource=readFileSync(new URL('../paper-engagement.ts',import.meta.url),'utf8');
 assert.match(engagementSource,/lti_paper_engagement_counts/);
 assert.match(engagementSource,/lti_my_paper_bookmarks/);
 assert.match(engagementSource,/lti_toggle_paper_bookmark/);
 assert.match(engagementSource,/lti_record_paper_view/);
 assert.match(engagementSource,/lti_record_paper_citation/);
 assert.match(engagementSource,/formatPaperCitation/);
 assert.doesNotMatch(detailSource,/なぜこのテーマに注目したのか/);
 assert.doesNotMatch(detailSource,/どのように調べ、何が見えてきたのか/);
 const cloudSource=readFileSync(new URL('../cloud.tsx',import.meta.url),'utf8');
 assert.match(cloudSource,/https:\/\/lti-explore-six\.vercel\.app\/\?flow=recovery/);
 assert.doesNotMatch(cloudSource,/lti-explore-lab-to-impact\.vercel\.app\/\?flow=recovery/);
 console.log('PASS: admin library separates hidden papers into archive; public library only shows published papers');
}finally{unlinkSync(path);}
