import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create schema storage;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('aal',coalesce(current_setting('test.aal',true),'aal1'))$$;
create table auth.sessions(id uuid,user_id uuid,created_at timestamptz);
create table auth.mfa_factors(user_id uuid,status text);
create table public.lti_profiles(id uuid,role text,school_id text,active boolean,must_change_password boolean,session_valid_after timestamptz default '-infinity');
create table public.lti_schools(id text,feature_settings jsonb default '{}');
create table public.lti_records(id text,kind text,owner_id uuid,school_id text,student_id text,status text,data jsonb);
create table public.lti_ai_usage(id bigserial,user_id uuid,mode text,created_at timestamptz default now());
create table public.lti_paper_views(user_id uuid,paper_id text,unique(user_id,paper_id));
create table public.lti_paper_citations(user_id uuid,paper_id text,unique(user_id,paper_id));
create table public.lti_paper_bookmarks(user_id uuid,paper_id text,unique(user_id,paper_id));
create table storage.objects(name text,bucket_id text);
create policy lti_pdf_delete on storage.objects for delete using(true);
grant usage on schema public,auth to authenticated,service_role;
`);
await db.exec(await readFile(new URL('auth-defs.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('hardening.sql',import.meta.url),'utf8'));
const student='00000000-0000-4000-8000-000000000001',teacher='00000000-0000-4000-8000-000000000002',admin='00000000-0000-4000-8000-000000000003';
await db.query(`insert into lti_profiles(id,role,school_id,active,must_change_password) values ($1,'student','A',true,false),($2,'teacher','B',true,false),($3,'admin',null,true,false)`,[student,teacher,admin]);
await db.exec(`insert into lti_schools(id) values('A'),('B');`);
await db.query(`insert into lti_records values ('published','papers',$1,'B',null,'公開中','{"status":"公開中"}'),('private','papers',$1,'B',null,'承認待ち','{"status":"承認待ち"}'),('submission','submissions',$1,'B',$1,'提出済','{}')`,[teacher]);
const asUser=async(uid,aal='aal1')=>{await db.query("select set_config('test.uid',$1,false),set_config('test.aal',$2,false)",[uid,aal]);};
const bool=async(sql,args=[]) => (await db.query(sql,args)).rows[0].ok;
await asUser(student);
assert.equal((await db.query("select lti_claim_ai_quota('review') n")).rows[0].n,null);
assert.equal(await bool("select lti_can_access_paper('published') ok"),true);
assert.equal(await bool("select lti_can_access_paper('private') ok"),false);
assert.equal(await bool("select lti_read_record(kind,owner_id,school_id,student_id,data) ok from lti_records where id='submission'"),false);
await db.exec(`update lti_schools set feature_settings='{"student:みんなの論文":"premium"}' where id='A'`);
assert.equal(await bool("select lti_can_access_paper('published') ok"),false);
await db.exec(`update lti_schools set feature_settings='{}';update lti_profiles set active=false where role='student'`);
assert.equal(await bool("select lti_can_access_paper('published') ok"),false);
await assert.rejects(()=>db.query("select lti_record_paper_view('published')"),/unavailable/);
assert.equal((await db.query("select * from lti_paper_engagement_counts(array['published'])")).rows.length,0);
await asUser(admin);
assert.equal(await bool("select lti_can_access_paper('private') ok"),false);
await asUser(admin,'aal2');assert.equal(await bool("select lti_can_access_paper('private') ok"),true);
await asUser(teacher);
await db.exec(`update lti_schools set feature_settings='{"teacher:AI添削":"premium"}' where id='B'`);
assert.equal((await db.query("select lti_claim_ai_quota('review') n")).rows[0].n,null);
await db.exec(`update lti_schools set feature_settings='{}' where id='B'`);
assert.equal(typeof (await db.query("select lti_claim_ai_quota('review') n")).rows[0].n,'number');
const object=teacher+'/paper.pdf';
await db.query("update lti_records set data=data||jsonb_build_object('storagePath',$1::text) where id='published'",[object]);
assert.equal(await bool("select lti_can_delete_document($1) ok",[object]),false);
assert.equal(await bool("select lti_can_delete_document($1) ok",[teacher+'/unused.pdf']),true);
assert.equal(await bool("select lti_can_delete_document($1) ok",[student+'/unused.pdf']),false);
await db.exec('set role authenticated');
await assert.rejects(()=>db.query('select lti_refund_ai_quota_internal(1,$1)',[teacher]),/permission denied/);
await db.exec('reset role');
await db.exec('truncate lti_ai_usage');
await db.query('insert into lti_ai_usage(id,user_id) values(1,$1)',[teacher]);
await db.exec('set role service_role');
assert.equal(await bool('select lti_refund_ai_quota_internal(1,$1) ok',[student]),false);
assert.equal(await bool('select lti_refund_ai_quota_internal(1,$1) ok',[teacher]),true);
assert.equal(await bool('select lti_refund_ai_quota_internal(1,$1) ok',[teacher]),false);
await db.close();
console.log('PASS: isolated Postgres tests: cross-school/private access, active/feature/MFA gates, file reference deletion guard, server-only owner-bound idempotent refund');
