import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table lti_profiles(id uuid primary key,name text,school_id text,role text,active boolean);
create table lti_schools(id text primary key,name text);
create function lti_role() returns text language sql stable as $$select role from public.lti_profiles where id=auth.uid() and active and (role<>'admin' or current_setting('test.aal',true)='aal2')$$;
create function lti_school() returns text language sql stable as $$select school_id from public.lti_profiles where id=auth.uid()$$;
grant usage on schema auth to authenticated;grant select on lti_profiles,lti_schools to authenticated;
insert into lti_schools values('A','School A'),('B','School B');
insert into lti_profiles values('00000000-0000-4000-8000-000000000001','Student','A','student',true),('00000000-0000-4000-8000-000000000002','Teacher','A','teacher',true),('00000000-0000-4000-8000-000000000003','Other','B','student',true),('00000000-0000-4000-8000-000000000004','Admin',null,'admin',true);`);
await db.exec(await readFile(new URL('../../supabase/support-messages.sql',import.meta.url),'utf8'));
const asUser=async(n,aal='aal1')=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false),set_config('test.aal',$2,false)",[`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,aal]);await db.exec('set role authenticated');};
const send=()=>db.query("insert into lti_support_messages(category,subject,body) values('その他','test','body') returning *");
await asUser(1);const m=(await send()).rows[0];assert.equal(m.school_name,'School A');assert.equal(m.sender_name,'Student');
await assert.rejects(()=>db.query("insert into lti_support_messages(category,subject,body,sender_id) values('その他','x','x','00000000-0000-4000-8000-000000000003')"));
assert.equal((await db.query("update lti_support_messages set status='対応済み' returning id")).rows.length,0);
await asUser(2);assert.equal((await db.query('select * from lti_support_messages')).rows.length,0);await send();
await asUser(3);assert.equal((await db.query('select * from lti_support_messages')).rows.length,0);
await asUser(4);assert.equal((await db.query('select * from lti_support_messages')).rows.length,0);
await asUser(4,'aal2');assert.equal((await db.query('select * from lti_support_messages')).rows.length,2);
await db.query("update lti_support_messages set status='対応中',reply='確認しました' where id=$1",[m.id]);
await assert.rejects(()=>db.query("update lti_support_messages set body='changed'"));
await asUser(1);assert.equal((await db.query('select reply from lti_support_messages')).rows[0].reply,'確認しました');
for(let i=0;i<9;i++)await send();await assert.rejects(send,/10件/);
await db.exec("reset role;update lti_profiles set active=false where role='student'");await asUser(1);assert.equal((await db.query('select * from lti_support_messages')).rows.length,0);await assert.rejects(send);
await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select * from lti_support_messages'));
console.log('PASS: sender isolation (including same-school teacher), admin MFA, immutable content/identity, replies, rate limit, inactive and anonymous denial');await db.close();
